/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseIcon: typeof import('./components/BaseIcon.vue')['default']
    CardBox: typeof import('./components/CardBox.vue')['default']
    CardBoxAlert: typeof import('./components/ejemplosPrueba/CardBoxAlert.vue')['default']
    CardBoxComponentTitle: typeof import('./components/CardBoxComponentTitle.vue')['default']
    CardBoxTitle: typeof import('./components/ejemplosPrueba/CardBoxTitle.vue')['default']
    Client: typeof import('./components/client/index.vue')['default']
    ComponentsHTML: typeof import('./components/ejemplosPrueba/componentsHTML.vue')['default']
    DeleteClient: typeof import('./components/client/components/DeleteClient.vue')['default']
    EditClient: typeof import('./components/client/components/EditClient.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    FormChangePassword: typeof import('./components/auth/profile/components/FormChangePassword.vue')['default']
    FormProfile: typeof import('./components/auth/profile/components/FormProfile.vue')['default']
    Login: typeof import('./components/auth/login/index.vue')['default']
    MsjRefreshLogin: typeof import('./components/MsjRefreshLogin.vue')['default']
    NewClient: typeof import('./components/client/components/NewClient.vue')['default']
    NewProduct: typeof import('./components/product/components/NewProduct.vue')['default']
    OverlayLayer: typeof import('./components/OverlayLayer.vue')['default']
    Product: typeof import('./components/product/index.vue')['default']
    Profile: typeof import('./components/auth/profile/index.vue')['default']
    Recovery: typeof import('./components/auth/recoverypassword/components/recovery.vue')['default']
    Recoverypassword: typeof import('./components/auth/recoverypassword/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionMain: typeof import('./components/SectionMain.vue')['default']
    SectionTitleLineWithButton: typeof import('./components/SectionTitleLineWithButton.vue')['default']
    TableClient: typeof import('./components/client/components/TableClient.vue')['default']
    TableProduct: typeof import('./components/product/components/TableProduct.vue')['default']
    UserAvatar: typeof import('./components/UserAvatar.vue')['default']
    UserCard: typeof import('./components/UserCard.vue')['default']
  }
}
