/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseIcon: typeof import('./components/BaseIcon.vue')['default']
    CardBox: typeof import('./components/CardBox.vue')['default']
    CardBoxAlert: typeof import('./components/ejemplosPrueba/CardBoxAlert.vue')['default']
    CardBoxTitle: typeof import('./components/CardBoxTitle.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    FormProfile: typeof import('./components/auth/profile/components/FormProfile.vue')['default']
    Login: typeof import('./components/auth/login/index.vue')['default']
    MsjRefreshLogin: typeof import('./components/MsjRefreshLogin.vue')['default']
    OverlayLayer: typeof import('./components/OverlayLayer.vue')['default']
    Profile: typeof import('./components/auth/profile/index.vue')['default']
    Recovery: typeof import('./components/auth/recoverypassword/components/recovery.vue')['default']
    Recoverypassword: typeof import('./components/auth/recoverypassword/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionMain: typeof import('./components/SectionMain.vue')['default']
    SectionTitleLineWithButton: typeof import('./components/SectionTitleLineWithButton.vue')['default']
    UserAvatar: typeof import('./components/UserAvatar.vue')['default']
    UserCard: typeof import('./components/UserCard.vue')['default']
  }
}
